[authors.mtk]
name = "Mikkel Troels Kongsted"
email = "mtkongsted@gmail.com"

[authors.tph]
name = "Theis Pieter Hollebeek"
email = "tphollebeek@gmail.com"

[authors.sfj]
name = "Simon From Jakobsen"
email = "sfja2004@gmail.com"