services:
  backend:
    image: docker.io/sfja/h5-mst-backend:latest
    ports:
      - "42069:5000"
  mosquitto:
    image: docker.io/eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - $PWD/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $PWD/mqtt_users:/mosquitto/config/mqtt_users

