name: Backend

on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container: sfja/h5-mst-ci:backend-ci
    steps:
    - uses: actions/checkout@v6
    - name: Check
      working-directory: ./backend
      run: make check
    - name: Build
      working-directory: ./backend
      run: make all
    - name: Test
      working-directory: ./backend
      run: make test

