name: Game

on:
  push:
    branches: [ "main" ]
    paths: [ "game/**", ".github/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: sfja/h5-mst-ci:game-ci
    steps:
    - uses: actions/checkout@v6
    - name: Check
      working-directory: ./game
      run: cargo check
    - name: Clippy
      working-directory: ./game
      continue-on-error: true
      run: cargo clippy -- -Dwarnings
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    container: sfja/h5-mst-ci:game-ci
    steps:
    - uses: actions/checkout@v6
    - name: Build
      working-directory: ./game
      run: cargo build
    - name: Test
      working-directory: ./game
      run: cargo test
    - uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
