name: verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y libmicrohttpd-dev
    - name: install llvm
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 22
    - name: versions
      run: |
        clang-22 --version
        clang-format-22 --version
    - name: check
      working-directory: ./backend
      run: make check CLANG_FORMAT=clang-format-22
    - name: build
      working-directory: ./backend
      run: make all CC=clang-22 LD=clang-22

