name: Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    container: sfja/h5-mst-ci-backend:1.0

    steps:
    - uses: actions/checkout@v4
    - name: check
      working-directory: ./backend
      run: make check
    - name: build
      working-directory: ./backend
      run: make all
    - name: test
      working-directory: ./backend
      run: make test

